export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

type Row<T> = T;
type Insert<T> = Partial<T>;
type Update<T> = Partial<T>;

export type Database = {
  public: {
    Tables: {
      user_profiles: { Row: Row<{ id: string; full_name: string | null; email: string | null; role: string; university: string | null; avatar_url: string | null; created_at: string; updated_at: string }>; Insert: Insert<Row<{ id: string; full_name?: string | null; email?: string | null; role?: string; university?: string | null; avatar_url?: string | null }>>; Update: Update<Row<{ full_name?: string | null; email?: string | null; role?: string; university?: string | null; avatar_url?: string | null }>>; Relationships: [] };
      user_study_data: { Row: { user_id: string; data: Json; created_at: string; updated_at: string }; Insert: { user_id: string; data?: Json }; Update: { data?: Json }; Relationships: [] };
      study_groups: { Row: { id: string; owner_id: string; name: string; subject: string; description: string | null; invite_code: string; is_private: boolean; created_at: string; updated_at: string }; Insert: { owner_id: string; name: string; subject: string; description?: string | null; invite_code: string; is_private?: boolean }; Update: Partial<{ name: string; subject: string; description: string | null; is_private: boolean }>; Relationships: [] };
      study_sessions: { Row: { id: string; user_id: string; session_type: "manual" | "pomodoro" | "flashcards"; subject: string; topic: string | null; task_id: string | null; duration_minutes: number; started_at: string; ended_at: string; metadata: Json; created_at: string }; Insert: { user_id: string; session_type?: "manual" | "pomodoro" | "flashcards"; subject?: string; topic?: string | null; task_id?: string | null; duration_minutes: number; started_at?: string; ended_at?: string; metadata?: Json }; Update: Partial<{ session_type: "manual" | "pomodoro" | "flashcards"; subject: string; topic: string | null; task_id: string | null; duration_minutes: number; started_at: string; ended_at: string; metadata: Json }>; Relationships: [] };
      pomodoro_sessions: { Row: { id: string; user_id: string; started_at: string; ended_at: string | null; planned_seconds: number; focused_seconds: number; status: "running" | "completed" | "abandoned"; subject: string | null; metadata: Json; created_at: string }; Insert: { user_id: string; started_at: string; planned_seconds: number; focused_seconds?: number; status?: "running" | "completed" | "abandoned"; subject?: string | null; metadata?: Json }; Update: Partial<{ ended_at: string | null; focused_seconds: number; status: "running" | "completed" | "abandoned"; subject: string | null; metadata: Json }>; Relationships: [] };
      flashcard_decks: { Row: { id: string; user_id: string; title: string; subject: string | null; description: string | null; cards: Json; source: "manual" | "ai" | "document" | "cloud"; created_at: string; updated_at: string }; Insert: { user_id: string; title: string; subject?: string | null; description?: string | null; cards?: Json; source?: "manual" | "ai" | "document" | "cloud" }; Update: Partial<{ title: string; subject: string | null; description: string | null; cards: Json; source: "manual" | "ai" | "document" | "cloud" }>; Relationships: [] };
      flashcards: { Row: { id: string; user_id: string; deck_id: string; card_key: string; question: string; answer: string; card_type: string; options: Json; explanation: string | null; tags: Json; position: number; created_at: string; updated_at: string }; Insert: { user_id: string; deck_id: string; card_key: string; question: string; answer: string; card_type?: string; options?: Json; explanation?: string | null; tags?: Json; position?: number }; Update: Partial<{ question: string; answer: string; card_type: string; options: Json; explanation: string | null; tags: Json; position: number }>; Relationships: [] };
      srs_progress: { Row: { id: string; user_id: string; deck_id: string; card_key: string; interval_days: number; ease_factor: number; repetitions: number; due_at: string; updated_at: string }; Insert: { user_id: string; deck_id: string; card_key: string; interval_days?: number; ease_factor?: number; repetitions?: number; due_at?: string }; Update: Partial<{ interval_days: number; ease_factor: number; repetitions: number; due_at: string }>; Relationships: [] };
      analytics_daily: { Row: { user_id: string; day: string; focused_minutes: number; sessions_completed: number; cards_reviewed: number; cards_mastered: number; xp_earned: number; streak_days: number; metadata: Json; updated_at: string }; Insert: { user_id: string; day: string; focused_minutes?: number; sessions_completed?: number; cards_reviewed?: number; cards_mastered?: number; xp_earned?: number; streak_days?: number; metadata?: Json }; Update: Partial<{ focused_minutes: number; sessions_completed: number; cards_reviewed: number; cards_mastered: number; xp_earned: number; streak_days: number; metadata: Json }>; Relationships: [] };
      dashboard_preferences: { Row: { user_id: string; layout: Json; widgets: Json; updated_at: string }; Insert: { user_id: string; layout?: Json; widgets?: Json }; Update: Partial<{ layout: Json; widgets: Json }>; Relationships: [] };
      chapter_attachments: { Row: { id: string; user_id: string; subject_id: string; chapter_id: string; storage_path: string; file_name: string; mime_type: string; file_size: number; created_at: string }; Insert: { user_id: string; subject_id: string; chapter_id: string; storage_path: string; file_name: string; mime_type: string; file_size?: number }; Update: Partial<{ storage_path: string; file_name: string; mime_type: string; file_size: number }>; Relationships: [] };
      user_integrations: { Row: { user_id: string; cloud_provider: string | null; cloud_account_ref: string | null; openai_vault_secret_ref: string | null; settings: Json; updated_at: string }; Insert: { user_id: string; cloud_provider?: string | null; cloud_account_ref?: string | null; openai_vault_secret_ref?: string | null; settings?: Json }; Update: Partial<{ cloud_provider: string | null; cloud_account_ref: string | null; openai_vault_secret_ref: string | null; settings: Json }>; Relationships: [] };
    };
    Views: Record<string, never>;
    Functions: { set_openai_vault_secret: { Args: { secret_value: string }; Returns: string } };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

export type Tables<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Row"];
export type TablesInsert<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Insert"];
export type TablesUpdate<T extends keyof Database["public"]["Tables"]> = Database["public"]["Tables"][T]["Update"];
